version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.main:app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge