networks:
  nginx_bridge:
    external: true

services:
  edgetts:
    build: .
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_ENV=production
      - API_KEY=${API_KEY}
    restart: unless-stopped
    networks:
      - nginx_bridge