networks:
  nginx_bridge:
    external: true

services:
  edgetts:
    build: .
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - nginx_bridge