name: Deploy to Server

on:
  push:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
            cd /opt/edge-tts
            git pull origin main
            echo "API_KEY=${{ secrets.API_KEY }}" > .env
            docker-compose down
            docker-compose up -d
            rm .env